import { NextResponse } from 'next/server'
import { snowflakeQuery } from '@/lib/snowflake'

// 글로벌 매장별 상품 TOP 20 (YTD + 전월 + 전주)
export async function GET() {
  try {
    const sql = `
      WITH base AS (
        SELECT sh.SHOPNM, sa.BRANDNM, st.STYLENM, sa.STYLECD, sa.COLORCD,
          COALESCE(MAX(sd.COLORNM), sa.COLORCD) AS COLORNM,
          SUM(sa.SALEAMT) AS YTD_AMT,
          SUM(sa.SALEQTY) AS YTD_QTY,
          SUM(CASE WHEN sa.SALEDT >= '20260301' AND sa.SALEDT < '20260401' THEN sa.SALEAMT ELSE 0 END) AS M03_AMT,
          SUM(CASE WHEN sa.SALEDT >= '20260301' AND sa.SALEDT < '20260401' THEN sa.SALEQTY ELSE 0 END) AS M03_QTY,
          SUM(CASE WHEN sa.SALEDT >= '20260323' AND sa.SALEDT < '20260330' THEN sa.SALEAMT ELSE 0 END) AS PW_AMT,
          SUM(CASE WHEN sa.SALEDT >= '20260323' AND sa.SALEDT < '20260330' THEN sa.SALEQTY ELSE 0 END) AS PW_QTY,
          SUM(sa.TAGPRICE * sa.SALEQTY) AS YTD_TAG,
          SUM(COALESCE(pc.PRECOST, st.PRODCOST, 0) * sa.SALEQTY) AS YTD_COGS
        FROM SW_SALEINFO sa
        JOIN SW_SHOPINFO sh ON sa.SHOPCD = sh.SHOPCD
        JOIN SW_STYLEINFO st ON sa.STYLECD = st.STYLECD AND sa.BRANDCD = st.BRANDCD
        LEFT JOIN (SELECT STYLECD, BRANDCD, AVG(PRECOST) AS PRECOST FROM SW_STYLEINFO_DETAIL GROUP BY STYLECD, BRANDCD) pc ON st.STYLECD = pc.STYLECD AND st.BRANDCD = pc.BRANDCD
        LEFT JOIN (
          SELECT DISTINCT STYLECD, COLORCD, BRANDCD, COLORNM FROM SW_STYLEINFO_DETAIL
        ) sd ON sa.STYLECD = sd.STYLECD AND sa.COLORCD = sd.COLORCD AND sa.BRANDCD = sd.BRANDCD
        WHERE (sh.AREACD IN ('TW','JP','CN','SA','CH') OR sa.SHOPCD = 'B6050')
          AND sa.SALEDT >= '20260101'
          AND sa.BRANDNM IN ('커버낫','와키윌리')
        GROUP BY sh.SHOPNM, sa.BRANDNM, st.STYLENM, sa.STYLECD, sa.COLORCD
        HAVING SUM(sa.SALEAMT) > 0
      ),
      ranked_ytd AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY SHOPNM, BRANDNM ORDER BY YTD_AMT DESC) AS RN FROM base),
      ranked_m03 AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY SHOPNM, BRANDNM ORDER BY M03_AMT DESC) AS RN FROM base WHERE M03_AMT > 0),
      ranked_pw AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY SHOPNM, BRANDNM ORDER BY PW_AMT DESC) AS RN FROM base WHERE PW_AMT > 0),
      combined AS (
        SELECT SHOPNM, BRANDNM, STYLENM, STYLECD, COLORCD, COLORNM, YTD_AMT, YTD_QTY, M03_AMT, M03_QTY, PW_AMT, PW_QTY, YTD_TAG, YTD_COGS FROM ranked_ytd WHERE RN <= 20
        UNION
        SELECT SHOPNM, BRANDNM, STYLENM, STYLECD, COLORCD, COLORNM, YTD_AMT, YTD_QTY, M03_AMT, M03_QTY, PW_AMT, PW_QTY, YTD_TAG, YTD_COGS FROM ranked_m03 WHERE RN <= 20
        UNION
        SELECT SHOPNM, BRANDNM, STYLENM, STYLECD, COLORCD, COLORNM, YTD_AMT, YTD_QTY, M03_AMT, M03_QTY, PW_AMT, PW_QTY, YTD_TAG, YTD_COGS FROM ranked_pw WHERE RN <= 20
      )
      SELECT SHOPNM, BRANDNM, STYLENM, STYLECD, COLORCD, COALESCE(COLORNM, COLORCD) AS COLORNM, YTD_AMT, YTD_QTY, M03_AMT, M03_QTY, PW_AMT, PW_QTY, YTD_TAG, YTD_COGS
      FROM combined
      ORDER BY SHOPNM, BRANDNM, YTD_AMT DESC
    `
    const rows = await snowflakeQuery(sql)
    return NextResponse.json({ rows, count: rows.length })
  } catch (err) {
    return NextResponse.json({ error: String(err), rows: [] }, { status: 500 })
  }
}
